Repository FinalProject-8/BackFinalProject, pull requests merged in 2023-04, with the labels that each got.

#24 Feat: 학습전략 서비스 - 조회 기능
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/strategy/controller/StrategyController.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/strategy/dto/response/StrategyDetailPageResponse.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/strategy/dto/response/StrategyPageResponse.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/strategy/dto/response/StrategyVideoDTO.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/strategy/repository/StrategyRepository.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/strategy/service/StrategyService.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/strategy/service/impl/StrategyServiceImpl.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/config/WebSecurityConfig.java
Labels: Type: Feature, Status: In Progress, Priority: Medium, For: API

#30 Feat:ryusun - 기출해설 등록&조회&파일 다운로드& 이미지 조회 구현
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/controller/CommentaryController.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/dto/CommentaryRequest.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/dto/CommentaryResponse.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/dto/Response.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/dto/VideoUrlRequest.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/dto/VideoUrlResponse.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/entity/Commentary.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/entity/CommentaryFile.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/entity/CommentaryVideo.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/entity/InstructorImg.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/repository/CommentaryFileRepository.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/repository/CommentaryRepository.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/repository/CommentaryVideoRepository.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/repository/InstructorImgRepository.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/service/CommentaryService.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/service/FileService.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/service/Impl/CommentaryServiceImpl.java
  BackFinalPriject - 복사본/src/main/java/com/example/backfinalpriject/admin/commentary/service/Impl/FileServiceImpl.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/entity/CommentaryFile.java
Labels: Type: Feature

#31 feat:ryusun - 기출해설부분 reupload
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/controller/CommentaryController.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/dto/CommentaryRequest.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/dto/CommentaryResponse.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/dto/Response.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/dto/VideoUrlRequest.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/dto/VideoUrlResponse.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/entity/Commentary.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/entity/CommentaryFile.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/entity/CommentaryVideo.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/entity/InstructorImg.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/repository/CommentaryFileRepository.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/repository/CommentaryRepository.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/repository/CommentaryVideoRepository.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/repository/InstructorImgRepository.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/service/CommentaryService.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/service/FileService.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/service/Impl/CommentaryServiceImpl.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/service/Impl/FileServiceImpl.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/distinction/repository/DivisionRepository.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/distinction/repository/SubjectRepository.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/exception/ErrorCode.java
Labels: Type: Feature

#32 Refactor: 파일 수정했습니다
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/dto/request/CommentaryRequest.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/dto/request/VideoUrlRequest.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/dto/response/CommentaryResponse.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/dto/response/Response.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/dto/response/VideoUrlResponse.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/entity/Commentary.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/entity/CommentaryVideo.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/service/CommentaryService.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/service/Impl/CommentaryServiceImpl.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/strategy/controller/StrategyController.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/member/controller/MemberController.java
Labels: Type: Maintenance, Status: Completed, Priority: Medium, For: Backend

#34 Feat: 기출해설 서비스 - 검색 기능 구현
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/controller/CommentaryController.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/dto/response/SearchResponse.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/repository/CommentaryRepository.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/service/CommentaryService.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/service/Impl/CommentaryServiceImpl.java
Labels: Type: Feature, Status: In Progress, Priority: Medium, For: API

#36 Conf : CORS 관련 설정 파일(WebConfig) 추가
  BackFinalPriject/src/main/java/com/example/backfinalpriject/config/WebConfig.java
Labels: Type: Feature, Status: In Progress, Priority: Critical, For: Backend

#37 Refactor: CommentaryRepository 파일 수정
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/repository/CommentaryRepository.java
Labels: Type: Maintenance, Status: In Progress, Priority: Medium, For: API

#40 Feat/ryusun- 기출해설페이지 수정 api 구현
  BackFinalPriject/build.gradle
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/controller/CommentaryController.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/dto/response/CommentaryResponse.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/entity/Commentary.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/entity/CommentaryFile.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/entity/CommentaryVideo.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/entity/InstructorImg.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/repository/CommentaryFileRepository.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/service/CommentaryService.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/service/FileService.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/service/Impl/CommentaryServiceImpl.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/admin/commentary/service/Impl/FileServiceImpl.java
  BackFinalPriject/src/main/java/com/example/backfinalpriject/config/WebSecurityConfig.java
Labels: Type: Feature
